# permissions for end users to view dexauthclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexauthclient-viewer-role
rules:
- apiGroups:
  - dex.xzzpig.com
  resources:
  - dexauthclients
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dex.xzzpig.com
  resources:
  - dexauthclients/status
  verbs:
  - get
