# permissions for end users to view dexclientorders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dexclientorder-viewer-role
rules:
- apiGroups:
  - dex.xzzpig.com
  resources:
  - dexclientorders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dex.xzzpig.com
  resources:
  - dexclientorders/status
  verbs:
  - get
